query getUser {
  user {
    id
    userName
  }
}

query getUsers {
  users {
    id
    userName
  }
}

query getPost {
  post (id: "7833") {
    __typename

    ... on Post {
      id
      title
    }

    ... on PostError {
      statusCode
      message

      ... on PostNotFoundError {
        postId
      }

      ... on PostTimeoutError {
        timeout
      }
    }
  }
}
